# Generated by Django 5.0.14 on 2025-05-12 10:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MTTB_Ccy_DEFN",
            fields=[
                (
                    "ccy_code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "Ccy_Name_la",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "Ccy_Name_en",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("Country", models.CharField(blank=True, max_length=20, null=True)),
                ("Ccy_Decimals", models.DecimalField(decimal_places=2, max_digits=12)),
                ("ALT_Ccy_Code", models.CharField(blank=True, max_length=2, null=True)),
                (
                    "Record_Status",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("Maker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Checker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Auth_Status", models.CharField(blank=True, max_length=1, null=True)),
                ("Once_Auth", models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                "verbose_name_plural": "Currency_DEFN_Info",
            },
        ),
        migrations.CreateModel(
            name="MTTB_Divisions",
            fields=[
                (
                    "div_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "division_name_la",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "division_name_en",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "record_Status",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("Maker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Checker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Auth_Status", models.CharField(blank=True, max_length=1, null=True)),
                ("Once_Auth", models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                "verbose_name_plural": "DivisionsInfo",
            },
        ),
        migrations.CreateModel(
            name="MTTB_Fin_Cycle",
            fields=[
                (
                    "fin_cycle",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("cycle_Desc", models.CharField(blank=True, max_length=250, null=True)),
                ("StartDate", models.DateTimeField(blank=True, null=True)),
                ("EndDate", models.DateTimeField(blank=True, null=True)),
                (
                    "Record_Status",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("Maker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Checker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Auth_Status", models.CharField(blank=True, max_length=1, null=True)),
                ("Once_Auth", models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                "verbose_name_plural": "FinCycle",
            },
        ),
        migrations.CreateModel(
            name="MTTB_Function_Desc",
            fields=[
                (
                    "function_id",
                    models.CharField(
                        max_length=20,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Function_Id",
                    ),
                ),
                ("description_la", models.CharField(max_length=200)),
                (
                    "description_en",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("all_link", models.CharField(blank=True, max_length=200, null=True)),
                ("eod_function", models.CharField(blank=True, max_length=1, null=True)),
                ("function_order", models.IntegerField(blank=True, null=True)),
                ("is_active", models.CharField(blank=True, max_length=1, null=True)),
                ("created_by", models.CharField(blank=True, max_length=30, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True, null=True)),
                ("modified_by", models.CharField(blank=True, max_length=30, null=True)),
                ("modified_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Function_Description",
                "ordering": ["function_id"],
            },
        ),
        migrations.CreateModel(
            name="MTTB_GLMaster",
            fields=[
                ("glid", models.AutoField(primary_key=True, serialize=False)),
                ("gl_code", models.CharField(blank=True, max_length=20, null=True)),
                ("gl_Desc_la", models.CharField(blank=True, max_length=250, null=True)),
                ("gl_Desc_en", models.CharField(blank=True, max_length=250, null=True)),
                ("glType", models.CharField(blank=True, max_length=1, null=True)),
                ("category", models.CharField(blank=True, max_length=1, null=True)),
                ("retal", models.CharField(blank=True, max_length=1, null=True)),
                ("ccy_Res", models.CharField(blank=True, max_length=1, null=True)),
                ("Res_ccy", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "Allow_BackPeriodEntry",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "pl_Split_ReqD",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "Record_Status",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("Maker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Checker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Auth_Status", models.CharField(blank=True, max_length=1, null=True)),
                ("Once_Auth", models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                "verbose_name_plural": "GLMaster",
            },
        ),
        migrations.CreateModel(
            name="MTTB_MAIN_MENU",
            fields=[
                (
                    "menu_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "menu_name_la",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "menu_name_en",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("menu_icon", models.CharField(blank=True, max_length=250, null=True)),
                ("menu_order", models.CharField(blank=True, max_length=3, null=True)),
                ("is_active", models.BooleanField(default=False)),
                ("created_by", models.CharField(blank=True, max_length=20, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_by", models.CharField(blank=True, max_length=20, null=True)),
                ("modified_date", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name_plural": "MAIN_MENU",
            },
        ),
        migrations.CreateModel(
            name="MTTB_Role_Master",
            fields=[
                (
                    "role_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "role_name_la",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "role_name_en",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "record_Status",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("Maker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Checker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Auth_Status", models.CharField(blank=True, max_length=1, null=True)),
                ("Once_Auth", models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                "verbose_name_plural": "Role_MasterInfo",
            },
        ),
        migrations.CreateModel(
            name="STTB_Dates",
            fields=[
                ("date_id", models.AutoField(primary_key=True, serialize=False)),
                ("insertToday", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "prev_Wroking_Day",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                (
                    "next_working_Day",
                    models.DateTimeField(auto_now_add=True, null=True),
                ),
                ("eod_time", models.CharField(max_length=1)),
            ],
            options={
                "verbose_name_plural": "EndOfDateInfo",
                "ordering": ["date_id"],
            },
        ),
        migrations.CreateModel(
            name="STTB_ModulesInfo",
            fields=[
                (
                    "module_Id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("module_name_la", models.CharField(max_length=250)),
                ("module_name_en", models.CharField(max_length=250)),
                (
                    "module_icon",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("module_order", models.CharField(blank=True, max_length=3, null=True)),
                ("is_active", models.CharField(max_length=1)),
                ("created_by", models.CharField(blank=True, max_length=30, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_by", models.CharField(blank=True, max_length=30, null=True)),
                ("modified_date", models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                "verbose_name_plural": "ModulesInfo",
            },
        ),
        migrations.CreateModel(
            name="MTTB_Per_Code",
            fields=[
                (
                    "period_code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("PC_StartDate", models.DateTimeField(blank=True, null=True)),
                ("PC_EndDate", models.DateTimeField(blank=True, null=True)),
                (
                    "Fin_cycle",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SAMCSYS.mttb_fin_cycle",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "PerCode",
            },
        ),
        migrations.CreateModel(
            name="MTTB_Role_Detail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("New_Detail", models.IntegerField(default=0)),
                ("Del_Detail", models.IntegerField(default=0)),
                ("Edit_Detail", models.IntegerField(default=0)),
                ("Auth_Detail", models.IntegerField(default=0)),
                (
                    "function_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SAMCSYS.mttb_function_desc",
                    ),
                ),
                (
                    "role_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SAMCSYS.mttb_role_master",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Role_Detail",
            },
        ),
        migrations.CreateModel(
            name="MTTB_SUB_MENU",
            fields=[
                (
                    "sub_menu_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("sub_menu_name_la", models.CharField(max_length=250)),
                ("sub_menu_name_en", models.CharField(max_length=250)),
                (
                    "sub_menu_icon",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "sub_menu_order",
                    models.CharField(blank=True, max_length=3, null=True),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_by", models.CharField(blank=True, max_length=20, null=True)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                ("modified_by", models.CharField(blank=True, max_length=20, null=True)),
                ("modified_date", models.DateTimeField(auto_now=True, null=True)),
                (
                    "menu_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SAMCSYS.mttb_main_menu",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "SUB_MENU",
            },
        ),
        migrations.AddField(
            model_name="mttb_function_desc",
            name="sub_menu_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="SAMCSYS.mttb_sub_menu",
            ),
        ),
        migrations.CreateModel(
            name="MTTB_Users",
            fields=[
                (
                    "user_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("user_name", models.CharField(max_length=250)),
                ("user_password", models.CharField(max_length=250)),
                ("user_email", models.CharField(blank=True, max_length=250, null=True)),
                ("user_mobile", models.CharField(blank=True, max_length=15, null=True)),
                ("User_Status", models.BooleanField(default=True)),
                ("pwd_changed_on", models.DateField(blank=True, null=True)),
                ("InsertDate", models.DateTimeField(auto_now_add=True)),
                ("UpdateDate", models.DateTimeField(auto_now=True)),
                ("Maker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Checker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Auth_Status", models.CharField(blank=True, max_length=1, null=True)),
                ("Once_Auth", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "Checker_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checked_userss",
                        to="SAMCSYS.mttb_users",
                    ),
                ),
                (
                    "Maker_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_userss",
                        to="SAMCSYS.mttb_users",
                    ),
                ),
                (
                    "Role_ID",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SAMCSYS.mttb_role_master",
                    ),
                ),
                (
                    "div_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SAMCSYS.mttb_divisions",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "UsersRgith",
            },
        ),
        migrations.CreateModel(
            name="MTTB_TRN_Code",
            fields=[
                (
                    "trn_code",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "trn_Desc_la",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "trn_Desc_en",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "Record_Status",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("Maker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Checker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Auth_Status", models.CharField(blank=True, max_length=1, null=True)),
                ("Once_Auth", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "Checker_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checked_Trn_Code",
                        to="SAMCSYS.mttb_users",
                    ),
                ),
                (
                    "Maker_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_Trn_Code",
                        to="SAMCSYS.mttb_users",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "TrnCode",
            },
        ),
        migrations.AddField(
            model_name="mttb_role_master",
            name="Checker_Id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checked_roles",
                to="SAMCSYS.mttb_users",
            ),
        ),
        migrations.AddField(
            model_name="mttb_role_master",
            name="Maker_Id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_roles",
                to="SAMCSYS.mttb_users",
            ),
        ),
        migrations.CreateModel(
            name="MTTB_LCL_Holiday",
            fields=[
                (
                    "lcl_holiday_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("HYear", models.CharField(blank=True, max_length=4, null=True)),
                ("HMonth", models.CharField(blank=True, max_length=10, null=True)),
                ("HDate", models.DateTimeField(auto_now=True, null=True)),
                ("Holiday_List", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "Record_Status",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("Maker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Checker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Auth_Status", models.CharField(blank=True, max_length=1, null=True)),
                ("Once_Auth", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "Checker_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checked_TLCL_Holiday",
                        to="SAMCSYS.mttb_users",
                    ),
                ),
                (
                    "Maker_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_TLCL_Holiday",
                        to="SAMCSYS.mttb_users",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "LCL_Holiday",
            },
        ),
        migrations.CreateModel(
            name="MTTB_GLSub",
            fields=[
                ("glsub_id", models.AutoField(primary_key=True, serialize=False)),
                ("glsub_code", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "glsub_Desc_la",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "glsub_Desc_en",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                (
                    "Record_Status",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("Maker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Checker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Auth_Status", models.CharField(blank=True, max_length=1, null=True)),
                ("Once_Auth", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "gl_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SAMCSYS.mttb_glmaster",
                    ),
                ),
                (
                    "Checker_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checked_GL_sub",
                        to="SAMCSYS.mttb_users",
                    ),
                ),
                (
                    "Maker_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_GL_sub",
                        to="SAMCSYS.mttb_users",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "GLSub",
            },
        ),
        migrations.AddField(
            model_name="mttb_glmaster",
            name="Checker_Id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checked_GLMaster",
                to="SAMCSYS.mttb_users",
            ),
        ),
        migrations.AddField(
            model_name="mttb_glmaster",
            name="Maker_Id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_GLMaster",
                to="SAMCSYS.mttb_users",
            ),
        ),
        migrations.AddField(
            model_name="mttb_fin_cycle",
            name="Checker_Id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checked_Fin_Cycle",
                to="SAMCSYS.mttb_users",
            ),
        ),
        migrations.AddField(
            model_name="mttb_fin_cycle",
            name="Maker_Id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_Fin_Cycle",
                to="SAMCSYS.mttb_users",
            ),
        ),
        migrations.CreateModel(
            name="MTTB_EXC_Rate_History",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Buy_Rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("Sale_Rate", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "INT_Auth_Status",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("Maker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Checker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Auth_Status", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "ccy_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SAMCSYS.mttb_ccy_defn",
                    ),
                ),
                (
                    "Checker_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checked_Exc_Rate_History",
                        to="SAMCSYS.mttb_users",
                    ),
                ),
                (
                    "Maker_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_Exc_RateHistory",
                        to="SAMCSYS.mttb_users",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ExchangeRate_History",
            },
        ),
        migrations.CreateModel(
            name="MTTB_EXC_Rate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Buy_Rate", models.DecimalField(decimal_places=2, max_digits=12)),
                ("Sale_Rate", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "INT_Auth_Status",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("Maker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Checker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Auth_Status", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "ccy_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SAMCSYS.mttb_ccy_defn",
                    ),
                ),
                (
                    "Checker_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checked_Exc_Rate",
                        to="SAMCSYS.mttb_users",
                    ),
                ),
                (
                    "Maker_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_Exc_Rate",
                        to="SAMCSYS.mttb_users",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "ExchangeRate",
            },
        ),
        migrations.AddField(
            model_name="mttb_divisions",
            name="Checker_Id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checked_division",
                to="SAMCSYS.mttb_users",
            ),
        ),
        migrations.AddField(
            model_name="mttb_divisions",
            name="Maker_Id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_division",
                to="SAMCSYS.mttb_users",
            ),
        ),
        migrations.CreateModel(
            name="MTTB_DATA_Entry",
            fields=[
                (
                    "data_entry_id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                (
                    "JRN_REKEY_REQUIRED",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "JRN_REKEY_VALUE_DATE",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "JRN_REKEY_AMOUNT",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                (
                    "JRN_REKEY_TXN_CODE",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("BACK_VALUE", models.IntegerField(default=0)),
                ("MOD_NO", models.IntegerField(default=0)),
                (
                    "Record_Status",
                    models.CharField(blank=True, max_length=1, null=True),
                ),
                ("Maker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Checker_DT_Stamp", models.DateTimeField(blank=True, null=True)),
                ("Auth_Status", models.CharField(blank=True, max_length=1, null=True)),
                ("Once_Auth", models.CharField(blank=True, max_length=1, null=True)),
                (
                    "Checker_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checked_DATA_Entry",
                        to="SAMCSYS.mttb_users",
                    ),
                ),
                (
                    "Maker_Id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_DATA_Entry",
                        to="SAMCSYS.mttb_users",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "DATA_Entry",
            },
        ),
        migrations.AddField(
            model_name="mttb_ccy_defn",
            name="Checker_Id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="checked_Ccy_DEFN",
                to="SAMCSYS.mttb_users",
            ),
        ),
        migrations.AddField(
            model_name="mttb_ccy_defn",
            name="Maker_Id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_Ccy_DEFN",
                to="SAMCSYS.mttb_users",
            ),
        ),
        migrations.CreateModel(
            name="STTB_Current_Users",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Host_UserLogin", models.CharField(max_length=255)),
                ("Start_time", models.DateTimeField(auto_now_add=True, null=True)),
                (
                    "user_id",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="SAMCSYS.mttb_users",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Current_UserInfo",
            },
        ),
        migrations.AddField(
            model_name="mttb_main_menu",
            name="module_Id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="SAMCSYS.sttb_modulesinfo",
                verbose_name="module_Id",
            ),
        ),
    ]
